#!/usr/bin/env python3
"""
Convert a BeepBox .mid export into song-data.js for music.js.

    python midi_to_song.py BeepBox-Song.mid > song-data.js

Needs only Python 3 (no packages). Re-run it every time you re-export from BeepBox.

Assumes 16 steps (16th notes) per bar, same as the game. Each note is written as
[step within the bar (0-15), midi note, length in steps], one bar per line.
"""
import struct, sys

STEPS_PER_BAR = 16


def read_vlq(d, p):
    v = 0
    while True:
        b = d[p]; p += 1
        v = (v << 7) | (b & 0x7F)
        if not b & 0x80:
            return v, p


def parse(path):
    d = open(path, 'rb').read()
    if d[:4] != b'MThd':
        sys.exit('not a MIDI file')
    _, ntr, div = struct.unpack('>HHH', d[8:14])
    pos, tracks = 14, []
    tempo_us, timesig = 500000, (4, 4)
    for _ in range(ntr):
        ln = struct.unpack('>I', d[pos + 4:pos + 8])[0]
        p, end, pos = pos + 8, pos + 8 + ln, pos + 8 + ln
        t, rs, name, on, notes = 0, None, '', {}, []
        while p < end:
            dt, p = read_vlq(d, p); t += dt
            b = d[p]
            if b == 0xFF:
                ty = d[p + 1]; l, q = read_vlq(d, p + 2); data = d[q:q + l]; p = q + l
                if ty == 0x03: name = data.decode('latin1')
                elif ty == 0x51: tempo_us = int.from_bytes(data, 'big')
                elif ty == 0x58: timesig = (data[0], 2 ** data[1])
                continue
            if b in (0xF0, 0xF7):
                l, p = read_vlq(d, p + 1); p += l; continue
            if b & 0x80: rs = b; p += 1
            k, ch = rs >> 4, rs & 15
            if k in (0xC, 0xD): p += 1; continue
            a, v = d[p], d[p + 1]; p += 2
            if k == 9 and v > 0:
                on.setdefault((ch, a), []).append(t)
            elif k in (8, 9) and on.get((ch, a)):
                s = on[(ch, a)].pop(0); notes.append((s, t - s, a, ch))
        tracks.append((name, sorted(notes)))
    return div, tempo_us, timesig, tracks


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    div, tempo_us, (num, den), tracks = parse(sys.argv[1])
    bar_ticks = div * 4 * num // den
    step_ticks = bar_ticks / STEPS_PER_BAR
    step_sec = tempo_us / 1e6 * step_ticks / div
    bpm = round(60 / (4 * step_sec))               # tempo expressed as 16th-note BPM, like the game's BPM const
    last = max((s + l for _, ns in tracks for s, l, a, c in ns), default=0)
    bars = -(-last // bar_ticks)

    out = ['// Generated by midi_to_song.py from %s. Edit freely, or re-run the script.' % sys.argv[1].split('/')[-1],
           '// Each note: [step in bar (0-15), midi note, length in steps]. One line per bar.',
           'const SONG = {', '    bpm: %d,' % bpm, '    bars: %d,' % bars, '    tracks: {']
    drums = {}
    for name, ns in tracks:
        if not ns: continue
        key = name.replace(' channel', '').replace(' ', '')
        if ns[0][3] == 9:                              # drum channel: collect steps per drum note
            for s, l, a, c in ns:
                drums.setdefault(a, []).append(round(s / step_ticks))
            continue
        out.append('        %s: [' % key)
        for b in range(bars):
            row = []
            for s, l, a, c in ns:
                st = round(s / step_ticks) - b * STEPS_PER_BAR
                if 0 <= st < STEPS_PER_BAR:
                    row.append('[%d,%d,%d]' % (st, a, max(1, round(l / step_ticks))))
            out.append('            [%s],%s' % (','.join(row), '   // bar %d' % b if b % 4 == 0 else ''))
        out.append('        ],')
    out.append('    },')
    out.append('    drums: {   // midi drum note -> absolute steps (36 kick, 40 clap, 46 open hat, 55 hat)')
    for a in sorted(drums):
        out.append('        %d: [%s],' % (a, ','.join(str(x) for x in sorted(set(drums[a])))))
    out.append('    },')
    out.append('};')
    print('\n'.join(out))


main()
